FROM node:20-bookworm-slim

WORKDIR /app

ARG NODE_ENV
ARG VPS_ADMIN_DASHBOARD_PORT
ARG VPS_ADMIN_API_PORT
ARG VPS_DATA_DIR
ARG VPS_SMB_SHARE_ROOT
ARG VPS_ADMIN_WEB_ROOT
ARG VPS_API_TOKEN
ARG VPS_ADMIN_USERNAME
ARG VPS_ADMIN_PASSWORD
ARG VPS_ADMIN_SESSION_SECONDS
ARG VPS_SAMBA_MANAGE_ENABLED
ARG VPS_SAMBA_STREAMS_BACKEND
ARG VPS_SMB_PUBLIC_PORT
ARG VPS_SAMBA_CONF_DIR
ARG VPS_SAMBA_MAIN_CONF
ARG VPS_SAMBA_GENERATED_CONF
ARG VPS_SAMBA_INCLUDE_LINE
ARG VPS_SAMBA_RESTART_CMD
ARG VPS_MOUNT_MANAGE_ENABLED
ARG VPS_MOUNT_POLL_SECONDS
ARG VPS_RCLONE_CACHE_DIR
ARG VPSD_RCLONE_BINARY
ARG VPS_SFTP_PORT
ARG VPS_SFTP_USERNAME
ARG VPS_SFTP_PASSWORD
ARG VPS_SFTP_UID
ARG VPS_SFTP_GID
ARG VPS_POSTGRES_HOST
ARG VPS_POSTGRES_PORT
ARG VPS_POSTGRES_DATABASE
ARG VPS_POSTGRES_USER
ARG VPS_POSTGRES_PASSWORD
ARG VPS_POSTGRES_SSL_MODE

ENV NODE_ENV=${NODE_ENV} \
    VPS_ADMIN_DASHBOARD_PORT=${VPS_ADMIN_DASHBOARD_PORT} \
    VPS_ADMIN_API_PORT=${VPS_ADMIN_API_PORT} \
    VPS_DATA_DIR=${VPS_DATA_DIR} \
    VPS_SMB_SHARE_ROOT=${VPS_SMB_SHARE_ROOT} \
    VPS_ADMIN_WEB_ROOT=${VPS_ADMIN_WEB_ROOT} \
    VPS_API_TOKEN=${VPS_API_TOKEN} \
    VPS_ADMIN_USERNAME=${VPS_ADMIN_USERNAME} \
    VPS_ADMIN_PASSWORD=${VPS_ADMIN_PASSWORD} \
    VPS_ADMIN_SESSION_SECONDS=${VPS_ADMIN_SESSION_SECONDS} \
    VPS_SAMBA_MANAGE_ENABLED=${VPS_SAMBA_MANAGE_ENABLED} \
    VPS_SAMBA_STREAMS_BACKEND=${VPS_SAMBA_STREAMS_BACKEND} \
    VPS_SMB_PUBLIC_PORT=${VPS_SMB_PUBLIC_PORT} \
    VPS_SAMBA_CONF_DIR=${VPS_SAMBA_CONF_DIR} \
    VPS_SAMBA_MAIN_CONF=${VPS_SAMBA_MAIN_CONF} \
    VPS_SAMBA_GENERATED_CONF=${VPS_SAMBA_GENERATED_CONF} \
    VPS_SAMBA_INCLUDE_LINE=${VPS_SAMBA_INCLUDE_LINE} \
    VPS_SAMBA_RESTART_CMD=${VPS_SAMBA_RESTART_CMD} \
    VPS_MOUNT_MANAGE_ENABLED=${VPS_MOUNT_MANAGE_ENABLED} \
    VPS_MOUNT_POLL_SECONDS=${VPS_MOUNT_POLL_SECONDS} \
    VPS_RCLONE_CACHE_DIR=${VPS_RCLONE_CACHE_DIR} \
    VPSD_RCLONE_BINARY=${VPSD_RCLONE_BINARY} \
    VPS_SFTP_PORT=${VPS_SFTP_PORT} \
    VPS_SFTP_USERNAME=${VPS_SFTP_USERNAME} \
    VPS_SFTP_PASSWORD=${VPS_SFTP_PASSWORD} \
    VPS_SFTP_UID=${VPS_SFTP_UID} \
    VPS_SFTP_GID=${VPS_SFTP_GID} \
    VPS_POSTGRES_HOST=${VPS_POSTGRES_HOST} \
    VPS_POSTGRES_PORT=${VPS_POSTGRES_PORT} \
    VPS_POSTGRES_DATABASE=${VPS_POSTGRES_DATABASE} \
    VPS_POSTGRES_USER=${VPS_POSTGRES_USER} \
    VPS_POSTGRES_PASSWORD=${VPS_POSTGRES_PASSWORD} \
    VPS_POSTGRES_SSL_MODE=${VPS_POSTGRES_SSL_MODE}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    samba \
    samba-common-bin \
    samba-vfs-modules \
    openssh-server \
    rclone \
    fuse3 \
    ca-certificates \
    procps \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

COPY src ./src
COPY web ./web
COPY deploy/smb.conf.container /etc/samba/smb.conf
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN npm run admin:build

RUN chmod +x /usr/local/bin/entrypoint.sh \
    && mkdir -p /var/run/sshd /etc/samba/smb.conf.d/tm-adapter /data/vps/smb-share /mnt/tm-cloud /root/.config/rclone

EXPOSE 8787 8788 445 2222
VOLUME ["/data/vps", "/mnt/tm-cloud"]

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
