import type { DiskForm, MountForm, SettingsForm, UserForm, GroupForm, ProviderForm } from './types';

export const DEFAULT_DISK_FORM: DiskForm = {
  name: '',
  timeMachineEnabled: false,
  timeMachineQuotaGb: '0',
  accessMode: 'legacy-per-share',
  smbUserIds: '',
  smbGroupIds: '',
  sftpUserIds: '',
  sftpGroupIds: '',
  storageMode: 'local',
  storageMountId: '',
  storageSubdir: '',
  storagePath: '',
  shareName: '',
  smbUsername: '',
  smbPassword: '',
  sftpUsername: '',
  sftpPassword: '',
  applySamba: true,
  applySftp: true,
};

export const DEFAULT_MOUNT_FORM: MountForm = {
  name: '',
  provider: 's3',
  remotePath: '',
  mountPath: '',
  bucket: '',
  prefix: '',
  region: 'us-east-1',
  endpoint: '',
  accessKeyId: '',
  secretAccessKey: '',
  s3Provider: 'AWS',
  extraArgs: '',
  rcloneBinary: 'rclone',
  enabled: true,
  ensureMounted: false,
};

export const DEFAULT_SETTINGS_FORM: SettingsForm = {
  adminUsername: '',
  adminPassword: '',
  apiToken: '',
  adminSessionSeconds: '43200',
  hostname: '',
  rootShareName: 'timemachine',
  browseShareName: 'timemachine',
  browseShareEnabled: true,
  smbPublicPort: '445',
  smbEnabled: true,
  sftpEnabled: true,
  mountManagementEnabled: true,
  smbStreamsBackend: 'xattr',
  mountPollSeconds: '30',
  vpsCacheDir: '/data/vps/rclone-vfs-cache',
  vpsCacheEnabled: true,
  vpsWriteBackSeconds: '120',
  vpsCacheMaxSizeGb: '1',
  vpsCacheMaxAgeHours: '24',
  vpsReadAheadMb: '16',
  enterpriseFeaturesEnabled: false,
  adminAuthMode: 'local',
  smbAuthMode: 'local',
  sftpAuthMode: 'local',
  securityIpAllowlist: '',
  securityBreakGlassEnabled: true,
  securityAuditRetentionDays: '180',
  oidcIssuer: '',
  oidcClientId: '',
  oidcClientSecret: '',
  oidcScopes: 'openid profile email groups',
  oidcAdminGroup: '',
  oidcReadOnlyGroup: '',
  directoryDomain: '',
  directoryRealm: '',
  directoryUrl: '',
  directoryBindDn: '',
  directoryBindPassword: '',
  workgroupMappingsJson: '[]',
  mountPolicyMode: 'policy_templates',
  postgresEnabled: true,
  postgresHost: 'postgres',
  postgresPort: '5432',
  postgresDatabase: 'tm_adapter',
  postgresUser: 'tm_adapter',
  postgresPassword: '',
  postgresSslMode: 'disable',
};

export const DEFAULT_USER_FORM: UserForm = {
  username: '',
  displayName: '',
  authType: 'local',
  password: '',
  protocolUsername: '',
  protocolPassword: '',
  groupIds: '',
  enabled: true,
  isAdmin: false,
  smbEnabled: true,
  sftpEnabled: true,
  identityProviderId: '',
  externalSubject: '',
};

export const DEFAULT_GROUP_FORM: GroupForm = {
  name: '',
  description: '',
  memberUserIds: '',
};

export const DEFAULT_PROVIDER_FORM: ProviderForm = {
  name: '',
  type: 'oidc',
  enabled: true,
  issuer: '',
  clientId: '',
  clientSecret: '',
  scopes: '',
  directoryUrl: '',
  directoryDomain: '',
  directoryRealm: '',
  directoryBindDn: '',
  directoryBindPassword: '',
};

export const MAX_DASHBOARD_LOGS = 1000;
export const MAX_TAIL_LINES = 4000;
export const DEFAULT_TAIL_LINE_COUNT = 200;
export const MAX_TERMINAL_CHARS = 160000;
